import { createClient } from '@/lib/supabase/client'

// Interfaces
export interface Organization {
  id: string
  internal_id?: string
  name: string
  hp?: string
  contact_name?: string
  contact_email?: string
  is_active: boolean
  modules?: string[]
  created_at: string
  updated_at: string
}

export interface OrgUser {
  id: string
  email: string
  name: string
  role: 'admin' | 'manager' | 'employee'
  org_id: string
}

class ApiClient {
  private supabase = createClient()

  // Organizations
  async getOrganizations() {
    const { data, error } = await this.supabase
      .from('organizations')
      .select('*')
      .order('created_at', { ascending: false })

    if (error) throw error
    return data as Organization[]
  }

  async createOrganization(org: { name: string; hp?: string; contact_name?: string; contact_email?: string; is_active: boolean; modules?: string[] }) {
    // Note: internal_id is generated by the database if the column exists and has a default/sequence
    const { data, error } = await this.supabase
      .from('organizations')
      .insert([org])
      .select()
      .single()

    if (error) throw error
    return data as Organization
  }

  async updateOrganization(id: string, updates: Partial<Organization>) {
    const { data, error } = await this.supabase
      .from('organizations')
      .update(updates)
      .eq('id', id)
      .select()
      .single()

    if (error) throw error
    return data as Organization
  }

  async deleteOrganization(id: string) {
    const { error } = await this.supabase
      .from('organizations')
      .delete()
      .eq('id', id)

    if (error) throw error
    return true
  }

  // Organization Users
  async getOrgUsers(orgId: string) {
    // Note: This requires a 'users' or 'organization_users' table which might not exist yet in the real DB.
    // For this simple implementation, we'll try to insert into a 'users' table or return empty if not found.
    // Typically users are handled via Supabase Auth and a public profiles table.

    const { data, error } = await this.supabase
      .from('users') // Assuming a users table in public schema
      .select('*')
      .eq('org_id', orgId)

    if (error) {
      console.warn('Error fetching users (table might not exist):', error)
      return []
    }
    return data as OrgUser[]
  }

  async createOrgUser(orgId: string, userData: { name: string; email: string; role: string }) {
    // In a real app this should create a Supabase Auth user + public profile
    // Here we just insert into 'users' table for simplicity as per requirement
    const { data, error } = await this.supabase
      .from('users')
      .insert([{ ...userData, org_id: orgId }])
      .select()
      .single()

    if (error) throw error
    return data as OrgUser
  }
}

export const api = new ApiClient()
